### ISSUE TITLE
Issue with unordered collections (e.g. JSON dictionaries)

### ISSUE THREAD

**Issue by AliSoftware** [krzysztofzablocki/Difference#1]
When comparing dictionaries, being unordered collections, the comparison isn't guaranteed because the Mirror doesn't guarantee listing children in a fixed order.

```swift
let x = try! JSONSerialization.jsonObject(with: "{ \"a\": 1, \"b\": 2 }".data(using: .utf8)!, options: [])
let y = try! JSONSerialization.jsonObject(with: "{ \"b\": 2, \"a\": 1 }".data(using: .utf8)!, options: [])
print("JSON comparison:\n" + diff(x, y).joined())
/* Console:
JSON comparison:
 received: "(key: b, value: 2)" expected: "(key: a, value: 1)"
 received: "(key: a, value: 1)" expected: "(key: b, value: 2)"
*/
```

Note that this works if instead of using `JSONSerialization` to build the dictionary I use a dictionary literal:

```swift
let xl: Any = ["a": 1, "b": 2]
let yl: Any = ["b": 2, "a": 1]
print("Literals diff:", diff(xl, yl))
/* Console:
Literals diff: []
*/
```
Probably a glitch of the Swift compiler always ordering the keys in the same order when parsing literals I guess, but we shouldn't rely on this glitch since the Dictionary contract doesn't guarantee that.

---

The problem is of course the same if we don't compare the dictionaries directly but compare two objets (say, structs) which happen to have a parameter (or a deeper children) being such a dictionary.

**Comment by AliSoftware** [comment]
Oh, it seems it's not because of JSON vs Literals, but because of Foundation types…

```swift
let xl: [NSString: NSNumber] = ["a": 1, "b": 2]
let yl: [NSString: NSNumber] = ["b": 2, "a": 1]
print("Foundation literals diff:\n" + diff(xl, yl).joined())
/* Console:
Foundation literals diff:
 received: "(key: b, value: 2)" expected: "(key: a, value: 1)"
 received: "(key: a, value: 1)" expected: "(key: b, value: 2)"
*/
```

Not sure what makes the compiler keep keys order on literals involving Foundation but not on ones involving pure Swift types… But anyway, the problem remains, as unordered collections don't guarantee the Mirror's children are gonna be the same for all equivalent instances anyway…

**Comment by krzysztofzablocki** [comment]
We can make specialisation for Diff generic and then just cast if its dict and reroute to it, that should work?

**Comment by AliSoftware** [comment]
Probably yeah. But diff-ing a `[AnyHashable: Any]` isn't built in in Swift so that requires a custom recursive implementation

**Comment by krzysztofzablocki** [comment]
@Ben-Henshall has made great improvements to how this work so this should work much nicer now
