### ISSUE TITLE
Difference package can't be integrated using version-based requirement

### ISSUE THREAD

**Issue by bielikb** [krzysztofzablocki/Difference#21]
# Description:
Difference package can't be integrated using [version-based requirement](https://developer.apple.com/documentation/swift_packages/package/dependency/requirement)

<img width="874" alt="Screenshot 2020-10-08 at 15 33 39" src="https://user-images.githubusercontent.com/4924709/95465644-b22f3e00-097b-11eb-9d58-c2793f5fb590.png">

Solution:
Follow semantic versioning in the releases of this Package.

**Comment by krzysztofzablocki** [comment]
maybe because it's tagged 0.5 not 0.5.0?

**Comment by bielikb** [comment]
yeah, that's the cause for the Xcode to fail -> so re-pushing tag with semantic version 0.5.0 will resolve the Xcode issue

**Comment by bielikb** [comment]
@krzysztofzablocki could you update your current tag `0.5` or create a new release that would follow the semantic versioning -> `0.5.0`?

Thanks!

**Comment by krzysztofzablocki** [comment]
done

**Comment by bielikb** [comment]
Perfect, thanks!
The issue was resolved ;)
