### ISSUE TITLE
Difference finds difference between two equally objects

### ISSUE THREAD

**Issue by subdan** [krzysztofzablocki/Difference#34]
Hello.

I have found a bug where `Difference` finds difference between two equally objects.

Example code that represents the issue:

```swift
import UIKit
import Difference

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        let vm1 = ViewModel(
            benchmarkValue: BenchmarkValue(state: .neutral),
            chartValue: ChartValue(values: [0, 0.5, 1], state: .neutral)
        )

        let vm2 = ViewModel(
            benchmarkValue: BenchmarkValue(state: .neutral),
            chartValue: ChartValue(values: [0, 0.1, 1], state: .neutral)
        )

        print(diff(vm1, vm2).joined(separator: ", "))
    }
}

struct ViewModel: Hashable {
    let benchmarkValue: BenchmarkValue
    let chartValue: ChartValue
}

struct BenchmarkValue: Hashable {
    var state: MetricState
}

enum MetricState: Hashable {
    case positive
    case warning
    case neutral
}

struct ChartValue: Hashable {
    let values: [Double]
    let state: MetricState
}
```

Actual output:
```
benchmarkValue:
|	state:
|	|	Received: 13108825602
|	|	Expected: 2
, chartValue:
|	state:
|	|	Received: 13108825602
|	|	Expected: 2
|	values:
|	|	Collection[1]:
|	|	|	Received: 0.1
|	|	|	Expected: 0.5
```

Expected output:
```
chartValue:
|	values:
|	|	Collection[1]:
|	|	|	Received: 0.1
|	|	|	Expected: 0.5
```

**Comment by subdan** [comment]
@krzysztofzablocki Hello. FYI there is no issue in 1.0.0 version. The issue did appear after [Add Objective-C enums support](https://github.com/krzysztofzablocki/Difference/commit/7897b35a39a20820194ef19585da90b7d24318f2) commit from @karolpiateknet.

**Comment by krzysztofzablocki** [comment]
@subdan ah that's good hint, maybe we can recognize if it's objective-c or standard enum and use old logic

**Comment by krzysztofzablocki** [comment]
@subdan found a workaround I think (it's meh but it works so it's good? 😂), let me know if it fixed it for you or you see anything funky, released in 1.0.2

**Comment by subdan** [comment]
Thank You, @krzysztofzablocki! Could you please release 1.0.2 version to CocoaPods?

**Comment by krzysztofzablocki** [comment]
@subdan done, sorry about that, forgot I still had cocoapods xD

**Comment by subdan** [comment]
It still 1.0.0 here https://cocoapods.org/pods/Difference and here https://github.com/krzysztofzablocki/Difference/blob/master/Difference.podspec

**Comment by krzysztofzablocki** [comment]
should be ok now

**Comment by subdan** [comment]
Yes, thanks!
