### ISSUE TITLE
String Difference

### ISSUE THREAD

**Issue by RLovelett** [krzysztofzablocki/Difference#9]
Is there any interest in adding `String` differencing to the library? Such that we could generate output similar to a unified diff?

```swift
let left = """
{
    "one": "two",
    "three": "four",
    "five": "six"
}
"""

let right = """
{
    "one": "two",
    "three":  "4",
    "five": "six"
}
"""

let diffs = diff(left, right)
```

So that `diffs` could provide values like this?

```patch
{
     "one": "two",
-    "three": "four",
+    "three":  "4",
     "five": "six"
 }
```

**Comment by krzysztofzablocki** [comment]
I'd be happy to accept a PR with something like this

**Comment by RLovelett** [comment]
Alright I’ve looked into some different algorithms and I’ve not found anything obvious yet.
